- .travis.yml
- ants/core/ants_image_io.py
- ants/lib/CMakeLists.txt
- ants/lib/LOCAL_antsImageHeaderInfo.cxx
- ants/lib/LOCAL_antsTransform.h
- ants/lib/LOCAL_cropImage.cxx
- ants/lib/LOCAL_readTransform.cxx
- ants/lib/ReadWriteData.h
- ants/lib/itkPyBuffer.hxx
- scripts/clone_itk.sh
- scripts/configure_ANTsPy.sh
- scripts/configure_ITK.sh
- scripts/configure_ITK_External_linux.sh
- scripts/configure_ITK_External_mac.sh
- tests/run_tests.sh
- tests/test_core_ants_image_io.py
- tests/test_utils.py
this PR expands on https://github.com/ANTsX/ANTsPy/pull/34 but it is too early for this to be merged.  it 
documents the COMP changes needed to get ANTsPy to compile with ITKv5, recent ANTs and the associated standards.   currently, the tests will fail due to failures of `ants.image_read( ... )`  detailed below:
```
import ants
img = ants.image_read( ants.get_data( "r16" ) )
ants.image_write( img, '/tmp/temp.nii.gz' )
img2 = ants.image_read( '/tmp/temp.nii.gz' )
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/stnava/code/ANTsPy/ants/core/ants_image_io.py", line 427, in image_read
libfn = utils.get_lib_fn(_image_read_dict[pclass][ptype][ndim])
KeyError: 'invalid'
```
the `KeyError` denotes that the reader is seeing an invalid pixeltype.   i do not, at …
> Itkv5compilation

- ants/registration/apply_transforms.py
Currently only the first transformation can be inverted if it is a matrix. This patch should allow all transformation matrices to be inverted.
> Fix index for inverting matrices

- ants/registration/build_template.py
- tests/test_registation.py
My bad, just found a typo: "tranform" instead of "transform".
> Fix typo from PR #66 and add test.

- ants/registration/interface.py
I noticed that simple "Rigid" would sometimes fail generating extremely large "spikes" in the motion corrected series, especially for small FOV datasets.
I haven't (so far) come across the issue after changing the type_of_transform to "BOLDRigid".
Are there any reasons why "BOLDRigid" should not be the default?
> Change motion correction default to BOLDRigid.

- ants/utils/convert_nibabel.py
Currently, to_nibabel only accepts 3D images. This PR lifts this restriction.
It also changes the usage of mktemp to the thread safe alternative mkstemp.
Should nibabel also be added to the requirements.txt?
> Lift 3d restriction to nibabel

- ants/utils/mask_image.py
Before, it was not possible to provide scalar types as the level argument since the for-loop that follows expects something we can iterate through.
Now, scalar arguments are converted to a list of one element which fixes the problem.
Please review carefully since I'm not a Python programmer!
> mask_image.py: Fix behavior of scalar level arguments

- ants/viz/plot.py
When plotting images on a grid, it's sometimes useful to
set all windows to the same min and max values for purposes of
comparison. The simplest way to do that is to set the window
limits using vmin and vmax.
> Add support for vmin, vmax in plot grid

- ants/viz/plot.py
Example:
```python
import ants
mni1 = ants.image_read(ants.get_data("mni"))
ants.plot_grid([[mni1, mni1],[mni1, mni1]], 
slices=100, vmax=[5000, 8000], clabels=["mni", "mni"], rlabels=["foo", "bar"])
```
> Add support for colorbar in plot_grid

- tutorials/InstallingANTsPy.md
This commit updates the macos and linux wheels from 0.1.4 to 0.1.8 and 0.2.0 respectively. 
I used the latest available for each. It is unclear to me why there is not a 0.2.0 release for both. The latest release with wheels available for both macos and linux os 0.1.7
> update wheel links in installation tutorial

- ants/viz/plot.py
There is an implicit assumption in the logic of viz.plot that it's input is
non-zero. While this is a reasonable assumption, calling viz.plot on a
zero-valued array results in an opaque IndexError.
Make the assumption explicit, and fail with the more descriptive AssertionError
"Image must be nonzero".
Resolves: #214
> Improve viz.plot's input validation

- docker/Dockerfile
- docker/README.md
This builds ANTsPy from source using pip. It makes a virtual environment first, which is then copied to the final layer. This makes for a smaller final image.
The base is the official Python Docker images, which are based on Debian.
> ENH: first try of a docker build

- ants/viz/plot.py
The plot function had a serious bug whereby resampling would introduce non-zero voxels and interfere with masking, leading to the appearance of wrong values.
This PR fixes this and introduces a couple of other improvements to the plot functionality of overlays, such as vminol and vmaxol parameters and a safer masking.
> Fix and improve plotting of overlays

- .github/workflows/wheels.yml
- scripts/configure_ANTsPy.bat
- scripts/configure_ITK.bat
- setup.py
- tests/run_tests.bat
This PR does 2 things:
1. Make it possible to compile to Windows. I did some change to `setup.py` and created the `bat` files to configure `ITK` and `AntPy`. I used [this tool](https://daniel-sc.github.io/bash-shell-to-bat-converter/) to help convert from shell to batch, but I needed to some conversions by hand. I tried these 2 tutorials (https://github.com/ANTsX/ANTsPy/blob/master/tutorials/Transform%20Generators.ipynb and https://github.com/ANTsX/ANTsPy/blob/master/tutorials/motionCorrectionExample.ipynb) and everything worked except the registration, it's showing this error:
```
file 0000021DE7BF8090 does not exist .
Exception Object caught:
itk::ExceptionObject (000000DE4EFE8360)
Location: "unknown"
File: C:\Users\Oscar\Sources\sss\ANTsPy\itksource\Modules\Registration\Common\include\i …
```
> Using Github CI to generate wheels and compiling to Windows too.

- Dockerfile
- tutorials/InstallingANTsPy.md
I've made a few changes to the `Dockerfile` to be able to build `linux/arm64` images with [native compatibility](https://docs.docker.com/desktop/mac/apple-silicon/) for M1 Apple Silicon.
Notably, `cmake` sourced from [github repo](https://github.com/Kitware/CMake/releases) would always fetch the `x86_64` binary even if the the defined `--platform` was not `linux/amd64`. Besides, the github repo didn't have native binaries for `ppc64le`. Therefore, the `ppc64le` build would fail even if a conditional `$architecture` variable was defined.
It made sense to replace the github binaries with the ones from the [anaconda repo](https://anaconda.org/anaconda/cmake) (`conda install -c anaconda cmake`) supporting multiple architectures, even if slightly outdated (`3.22.1` at the time of writing). …
> Fix multi-arch support for Dockerfile

- ants/segmentation/kelly_kapowski.py
When run as documented, specifying `its` as an integer does not work. KellyKapowski requires brackets, ie "-c [45]".
> BUG: kelly_kapowski its parameter needs brackets

- ants/segmentation/atropos.py
If the input list `i` for multivariate segmentation contains more than 9, that
is a double-digit number, of items, an error in filename format string
generation leads to an additional `0` being padded to the 10th filename during
creation.
```
ls /tmp/ants*
antsr6rhpmv2eprob01.nii.gz   antsr6rhpmv2eprob04.nii.gz  antsr6rhpmv2eprob08.nii.gz  antsr6rhpmv2eprob13.nii.gz
antsr6rhpmv2eprob010.nii.gz  antsr6rhpmv2eprob05.nii.gz  antsr6rhpmv2eprob09.nii.gz  antsr6rhpmv2eprob14.nii.gz
antsr6rhpmv2eprob02.nii.gz   antsr6rhpmv2eprob06.nii.gz  antsr6rhpmv2eprob11.nii.gz  antsr6rhpmv2eprob15.nii.gz
antsr6rhpmv2eprob03.nii.gz   antsr6rhpmv2eprob07.nii.gz  antsr6rhpmv2eprob12.nii.gz  antsr6rhpmv2eprob16.nii.gz
```
But the ANTs C extension expects the filename to only have two digits, not
three: …
> Draft: Segmentation fault in `atropos()` if more than 9 temporary files are created

- ants/registration/landmark_transforms.py
Hey @stnava , can you check this when you have some time?  Below is a toy example I've been using.  Note that the return value is a list of transforms with transforms[0] being the forward transform and transforms[1] being the reverse transform.
```python
import ants
domain_image = ants.image_read(ants.get_ants_data("r16"))
grid = ants.create_warped_grid(domain_image, grid_directions=(True, True))
fixed = np.array([[50.0,50.0],[200.0,50.0],[50.0,200.0]])
moving = np.array([[75.0,75.0],[175.0,75.0],[75.0,175.0]])
xfrms = ants.fit_transform_to_paired_points(moving, fixed, transform_type="syn", domain_image=domain_image, 
mesh_size=10, number_of_fitting_levels=6, number_of_compositions=100, composition_step_size=0.1)
warped_grid = xfrms[0].apply_to_image(grid) …
```
> WIP:  SyN landmarks.

- ants/lib/LOCAL_integrateVelocityField.cxx
- ants/registration/landmark_transforms.py
- ants/utils/integrate_velocity_field.py
- scripts/configure_ANTsPy.bat
- scripts/configure_ANTsPy.sh
- scripts/configure_ANTsPy_windows.sh
- scripts/configure_ITK.sh
- scripts/configure_ITK_External_linux.sh
Hey @stnava ,
When you get some time, it would be great if you could take a look.  I think I'm close on this one.  
```
import ants
fixed = np.array([[50.0,50.0],[200.0,50.0],[200.0,200.0]])
moving = np.array([[50.0,50.0],[50.0,200.0],[200.0,200.0]])
domain_image = ants.image_read(ants.get_ants_data("r16"))
xfrm = ants.fit_transform_to_paired_points(moving, fixed, transform_type="tv", 
domain_image=domain_image, number_of_fitting_levels=5, composition_step_size=10.0,
number_of_integration_points=4)
grid = ants.create_warped_grid(domain_image)
xfrm_forward = ants.transform_from_displacement_field(ants.integrate_velocity_field(xfrm, 0, 1))
ants.plot(ants.apply_ants_transform_to_image(xfrm_forward, grid, grid))
xfrm_inverse = …
```
> WIP:  Time-varying transform for landmarks.

- .cirrus.yml
- .dockerignore
- .github/workflows/wheels.yml
- Dockerfile
- ants/core/ants_image.py
- environment.yml
- requirements.txt
All docker images and wheels are built and test (`tests/build_wheels.sh`) successfully using Cirrus CI with a few exceptions (summarized in the Table below):
- `linux_aarch64`: no `py36` and `py311` wheels . `py36` fails while building `scikit-image` since no `py36` wheels exists on PyPI, and `py311` errors out while building `antspyx` possibly due to `pybind11`
- `macosx_arm64`: `cibuildwheel` on Apple Silicon only supports `py37+`. `py311` fails to build with the error similar to the one described above. The default deployment target is `macosx_11` or higher
- `docker`: both `arm64` and `x86_64` images are built and then unified into a single docker image
|   | Linux aarch64 | macOS Apple Silicon | Docker |
|---------------|:----:|:----:|:----:|
| CPython 3.6   | ❌ | N/A | N/A  | 
| …
> native `arm64` docker images + wheel builds for `linux_aarch64` and `macosx_arm64` using Cirrus CI

- .github/workflows/wheels.yml
Testing if this will work with an update to cibuildwheel version
Also update the python setup app to avoid Github deprecation warnings
> COMP: Add support for python 3.11, remove 3.6 from CI build wheels

- .github/workflows/wheels.yml
Updated the actions to create python 3.11 wheels too.
> Generate python 3.11 wheels

- .github/workflows/wheels.yml
This will upload the wheels to releases.
The wheel naming is a bit strange, the wheel name is not explicitly set by the user in the call to cibuildwheel.
> WIP: attach wheels to releases

- ants/registration/interface.py
* Added two optional inputs to `ants.registration`:
- `moving_mask` - a mask that applies to the moving image (default: `None`)
- `mask_all_stages` - if `True`, mask(s) are applied during all stages of registration (eg Affine *and* SyN). Otherwise (default) they are only applied at the last stage (usually SyN) as was the original behaviour.
* Slightly simplified the code for providing masks (or `"NA"` if none is provided) as arguments,
> Support for a slightly more flexible use of masks

- ants/utils/bias_correction.py
More general than a fixed spacing
Fixes #453
> ENH: default n3 / n4 spline mesh size of 1

- ants/lib/CMakeLists.txt
- ants/lib/LOCAL_antsTransform.h
- ants/lib/LOCAL_readTransform.cxx
- ants/lib/WRAP_AverageAffineTransform.cxx
- ants/lib/WRAP_AverageAffineTransformNoRigid.cxx
- ants/lib/__init__.py
- ants/lib/register_transforms.h
- ants/registration/build_template.py
- ants/utils/__init__.py
- ants/utils/average_transform.py
Also support for templates without nonlinear registration.
> updated build_template with affine shape correction 

- ants/lib/LOCAL_mergeChannels.cxx
`antsRegistration` writes double by default, supporting split / merge operations on vector images with pixel type double will simplify reading these warps into ANTsPy.
> ENH: Support vector images stored as double

- ants/core/ants_metric_io.py
- ants/lib/LOCAL_antsImageToImageMetric.h
- ants/utils/image_similarity.py
`utils.image_similarity` was returning MI metric value instead.
Fixes #479
> Similarity option typo made "ANTSNeighborhoodCorrelation" unreachable

- ants/contrib/sampling/affine2d.py
- ants/contrib/sampling/affine3d.py
Some of the docstrings for affine transformations were incorrect (probably due to copy-paste). This should hopefully be more clear!
> corrected docstrings for affine transformations

- ants/registration/apply_transforms.py
- ants/registration/resample_image.py
> STYLE: Remove unused CLI mangling code

- .cirrus.yml
- .github/workflows/wheels.yml
- Dockerfile
- setup.py
All tests passing and building successfully:
- wheels (`linux_aarch64` and `macos_arm64`)
- docker (`linux_aarch64` and `linux_amd64`) 
Wheels (and detailed logs) can be found here: https://cirrus-ci.com/build/5424545834729472
I haven't tested the `amd64` wheels for Windows/Linux/MacOS due to concurrency limits on Cirrus CI, but GitHub Actions should fill in the gap.
> COMP: Add support for Python 3.12

- ants/core/ants_transform.py
makes interpolation case insensitive for `apply_to_image` and adds the options to the docs
> make interpolation case-insensitive

- ants/utils/__init__.py
- ants/utils/histogram_equalize_image.py
Not sure if we already have this.
> ENH:  Histogram equalization

- ants/segmentation/kelly_kapowski.py
For example, BIDS common image-derived labels do not follow the same numbering scheme as ANTs. Add the ability to specify the GM and WM labels, retaining defaults GM=2 and WM=3
> ENH: Support different segmentation labels in kelly_kapowski

- .github/workflows/wheels.yml
- tests/run_tests.sh
- tests/test_viz.py
See if installing libpng beforehand helps
> Test viz png

- ants/segmentation/atropos.py
Raise an exception if the call to Atropos does not return normally, and avoid out of bounds error.
Addresses #554
> ENH: More specific error messages if atropos fails

- .github/workflows/wheels.yml
Set Intel Mac OS builds to OS 12, because I expect 'macos-latest' will switch over to arm64 at some point
> ENH: ARM64 builds

- ants/viz/plot.py
If an image has a sum less than zero, then `ants.plot` rejects it. This is due to code that incorrectly identifies whether an image is all-zero. 
This should work:
```python
import ants
img = ants.image_read(ants.get_ants_data('r16'))
img2 = (img - img.mean()) / img.std()
img2.plot()
```
> fix issue with plotting negative-sum images

- ants/utils/slice_image.py
Both axis and idx are required for `ants.slice_image` - the function fails without them. This pr removes the optionality of those args from the function signature.
> change required slice_image args

- .github/workflows/wheels.yml
Intel Mac runners failing suddenly
> COMP: Debugging output in runners

- ants/segmentation/kelly_kapowski.py
If the library call to `KellyKapowski` goes wrong for any reason, the function `kelly_kapowski` returned a copy of the input gray matter image.
To avoid this, I initialized the output image to zeros, then added a check to raise an exception if the thickness image to be returned sums to zero.
> ENH: avoid kelly_kapowski returning GMP

- ants/viz/plot_grid.py
- tests/test_viz.py
adds tests for plot_grid and supports 2d images
> test plot grid and support 2d images

- ants/core/ants_image.py
- tests/test_utils.py
The `decrop_image` function was not able to be called in a chaining manner as all other image-related functions (including `crop_image`) can be. This PR fixes that without breaking any existing code. 
The function still works exactly the same, but can now be optionally called directly from an image like this:
```python
mni = ants.image_read(ants.get_ants_data('mni'))
mni_crop = mni.crop_image()
mni_decrop = mni_crop.decrop_image(mni) # this didnt work previously
mni_decrop = ants.decrop_image(mni_crop, mni)
```
> allow decrop_image to be chained

- scripts/clone_itk.sh
- scripts/configure_ANTsPy.bat
- scripts/configure_ANTsPy.sh
- scripts/configure_ANTsPy_windows.sh
- scripts/configure_ITK.bat
- scripts/configure_ITK.sh
- scripts/configure_ITK_External_linux.sh
- setup.py
Bumps antspy to v0.5.0 and use the latest ants and itk commit hashes for building. We'll see if it's this simple...
Eventual general release notes:
- improved testing 
- minor bug fixes
- minor documentation improvements
- upgrade to latest ANTs and ITK version
- removed deprecated code (VTK-related visualization)
Things to accomplish during v0.5.x
- rework docs and tutorials (to ants.dev)
- reduce build size
- refactor ants.plot function to be simpler
- speed up import time (by deferring imports?)
> antspy to v0.5.0 and bump ants + itk versions to latest commit hashes

- .github/workflows/ci-pytest.yml
- .github/workflows/wheels_faster.yml
* Main one is a new script to quickly test python-only changes using cached wheels
* Duplicate wheels.yml because I can't figure out how to set matrix dynamically, and build a subset of wheels on push to master
* Set main wheels.yml to build the full matrix nightly, or upon release creation
Fixes #567
> ENH: Multiple CI changes

- ants/registration/apply_transforms.py
- tests/test_core_ants_transform.py
- tests/test_registation.py
Fixes #574 
I made an option to use single float precision, with default False. For long 4D time series, the memory requirements can be quite large, so it's good to be able to use float.
> Use double precision by default in apply_transforms computations

- ants/lib/LOCAL_antsImage.h
- ants/lib/LOCAL_cropImage.cxx
- ants/lib/LOCAL_padImage.cxx
- ants/utils/pad_image.py
- tests/test_core_ants_image.py
- tests/test_utils.py
Fixes #584, more background in #582
> ENH: Reset index after ITK filters, keep ITK object and python interface consistent

- .github/workflows/code-coverage.yml
Bumping the version, hoping to avoid coverage errors.
On coveralls.io, docstrings are being interpreted as uncovered code. This seems to only be a problem on multi-line function definitions.
https://coveralls.io/builds/66464549/source?filename=home%2Frunner%2F.local%2Flib%2Fpython3.10%2Fsite-packages%2Fants%2Fsegmentation%2Fatropos.py
I don't see this issue on my local machine if I run the tests
> ENH: Update coveralls version

- .github/workflows/code-coverage.yml
- tests/run_tests.sh
coveralls recommends xml if the output is not being interpreted correctly
> ENH: Use XML for coverage

- .github/workflows/ci-pytest.yml
Needs to invalidate cache if configure scripts change (often implies ITK / ANTs bump)
> BUG: Cache key had wrong path to config scripts

- scripts/configure_ANTsPy.bat
- scripts/configure_ANTsPy.sh
- scripts/configure_ANTsPy_windows.sh
> ENH: Version bump to fix imath segfault

- ants/utils/__init__.py
- ants/utils/histogram_match_image.py
Example.  Be sure to compare the actual source and transformed source images.
```python
import ants
from matplotlib import pyplot
source_image = ants.image_read(ants.get_ants_data("r16"))
source_mask = ants.get_mask(source_image)
reference_image = ants.image_read(ants.get_ants_data("r64"))
reference_mask = ants.get_mask(reference_image)
tx_source_image = ants.histogram_match_image2(source_image, reference_image, 
source_mask, reference_mask,
match_points=64,
transform_domain_size=255)
x = source_image[source_mask != 0].flatten()
y = reference_image[reference_mask != 0].flatten()
tx = tx_source_image[source_mask != 0].flatten()
pyplot.hist([x, y, tx], 64, alpha=0.5, label=["Source", "Ref", "Tx"])
pyplot.legend(loc="upper right")
pyplot.show()
```
> ENH:  Add masked/bspline fitting variant of Nyul histogram matching.

- ants/viz/plot_ortho.py
The `plot_ortho` function should not return anything. And this function gives an Unbound Local Error if there is no overlay supplied.
> FIX: remove plot_ortho return statement

- ants/registration/resample_image.py
- tests/test_registration.py
This PR adds support for multi-channel images in `resample_image`. The docstring says it's supported and there has pretty much always been an exception raised for multi-channel, so I think I just never got around to implementing it.
This implementation is the simplest - it just splits the channels and resamples on each of them individually. I think the ants function `ResampleImage` supports vector images natively, so that may be preferred in the future.
> ENH: support resampling multi-channel images

- ants/registration/interface.py
- tests/test_registration.py
- tests/test_segmentation.py
- tests/test_viz.py
> add more tests

- ants/core/ants_image.py
- ants/core/ants_image_io.py
- ants/core/ants_transform.py
- ants/core/ants_transform_io.py
- ants/registration/reorient_image.py
- ants/segmentation/anti_alias.py
- ants/utils/add_noise_to_image.py
- ants/utils/channels.py
- ants/utils/compose_displacement_fields.py
- ants/utils/crop_image.py
- ants/utils/fit_bspline_displacement_field.py
- ants/utils/fit_bspline_object_to_scattered_data.py
- ants/utils/fit_thin_plate_spline_displacement_field.py
- ants/utils/histogram_match_image.py
- ants/utils/integrate_velocity_field.py
- ants/utils/invert_displacement_field.py
- ants/utils/pad_image.py
- ants/utils/scalar_rgb_vector.py
- ants/utils/simulate_displacement_field.py
- ants/utils/slice_image.py
- ants/utils/smooth_image.py
- ants/utils/weingarten_image_curvature.py
- src/antsImage.cxx
- src/antsImage.h
Currently, you have to manually input a bunch of extra information when creating an ANTsImage internally from an ITK pointer, e.g.:
```python
img = iio.ANTsImage(pixeltype='float', dimension=2, components=1, pointer=itk_image)
```
Information such as pixeltype, dimension, components, is_rgb, etc is not only redundant to what is contained in the pointer, it is also vulnerable to bugs because it is not coupled to the one source of truth (the pointer to the actual image). If someone input the wrong dimension.. it would not be caught. 
This PR makes it so ANTsImage instances are created from only the pointer and all that extra info is extracted from the pointer. It is more robust and also makes it eventually easier to refactor the internal import system. The above line would be replaced with …
> ENH: initialize ANTsImage with pointer only

- ants/core/ants_transform_io.py
- tests/test_core_ants_transform_io.py
Very small pr that checks that the object passed into `write_transform` is actually an antstransform instance and provides a more informative error message.
> ENH: check for transform instance before writing to file

- ants/core/ants_transform_io.py
- tests/test_core_ants_transform_io.py
Related to #636, allow the read_transform function to read displacement fields.
Also added checking for the `transform_from_displacement_field` function, so that a meaningful error is raised if the image does not have the correct number of components.
> Ants read warp transform

- tests/common.py
Print status of individual tests and trace system errors on exit.
> ENH: Verbose tests

- CMakeLists.txt
- ants/core/ants_image.py
- ants/ops/weingarten_image_curvature.py
- ants/plotting/plot_grid.py
- src/antsGetItem.cxx
- src/main.cpp
- tests/run_tests.sh
- tests/test_core_ants_image.py
- tests/test_core_ants_image_indexing.py
Previously, indexing an ants image always returned a numpy array. This fix ensures that an ants image is returned where possible. No changes are made to indexing with another ants image or to setting behavior.
> FIX: image indexing returns image where possible

- ants/utils/matrix_image.py
- tests/test_core_ants_image_io.py
- tests/test_registration.py
Prevents cryptic error if the mask is not binarized, because the threshold was being applied to the numpy matrix but not the mask itself.
Also add some more tests
> ENH: Threshold mask in images_to_matrix

- ants/ops/slice_image.py
- tests/run_tests.sh
- tests/test_ops.py
The `slice_image` function currently does not support 2D images but it should. This PR changes that.
> ENH: support 2d images on slice_image function

- ants/core/__init__.py
- ants/core/ants_image_io.py
- tests/test_core_ants_image.py
The `new_image_like` function had a typo where the argument was name "self" because it was originally attached to the ants image class. Now it is an `@image_method` function. This PR fixes that and also adds a semi-alias function `from_numpy_like` that fit in better with the api given the `from_numpy` function... except the args are switched.
> FIX: new_image_like arg typo

- src/antsTransform.h
- tests/test_bugs.py
This PR lets you compose transforms of multiple types. There are really only two types of transforms wrapped by antspy though: itk::Transform and itk::DisplacementFieldTransform.
This example should work:
```python
import ants
image = ants.image_read(ants.get_ants_data("r16"))
linear_transform = ants.create_ants_transform(transform_type="AffineTransform", precision='float', 
dimension=image.dimension)
translation = (30,30)
translation_matrix = np.array([[1, 0, translation[0]], [0, 1, translation[1]]])
linear_transform.set_parameters(translation_matrix)
displacement_field = ants.simulate_displacement_field(image, field_type="bspline", 
number_of_random_points=10000, sd_noise=20.0, enforce_stationary_boundary=True, 
number_of_fitting_levels=4, mesh_size=2, …
```
> FIX: compose multi type transforms

- ants/ops/slice_image.py
- tests/test_ops.py
I realized that setting `axis = -1` in `slice_image()` caused a seg fault, so I am adding better error catching for the axis and supporting the axis=-1 as many other libraries do. I also need to be able to slice vector images so I implemented that.
> Fix: raise for bad slice axis; ENH: support slicing vector images

- ants/registration/fit_bspline_object_to_scattered_data.py
- tests/test_bugs.py
This changes helps support some potential existing code that had a 2-dimensional data_weights input.
> ENH: squeeze data_weights if necessary

- ants/core/ants_image.py
- ants/utils/channels.py
- tests/test_utils.py
We need a good way to specify whether to put the channels first or last when converting a vector image to numpy. This is a basic step in that direction by adding the `channels_first` property to ants images. It defaults to False, which is the current behavior of putting the channels last.
> ENH: support channels first for vector images

- ants/core/ants_image.py
- tests/test_core_ants_image.py
It was previously not possible to pickle ants images, so things like `deepcopy` failed. This PR adds basic pickle support via numpy. I had some random segfaults in some early versions of this PR but I believe the current version works well... something to keep an eye on anyways.
Example:
```python
import ants
import pickle
from copy import deepcopy
img = ants.image_read( ants.get_ants_data("r16"))
img_pickled = pickle.dumps(img)
img2 = pickle.loads(img_pickled)
img3 = deepcopy(img)
img += 10
print(img.mean(), img2.mean())
print(img.mean(), img3.mean())
```
> ENH: support pickle and deepcopy for images

- tests/test_bugs.py
This adds a test for the previous bspline zeros bug which is now fixed.. just to be sure for the future.
> TESTS: add test for bspline zeros bug

- ants/ops/iMath.py
- ants/ops/reorient_image.py
- ants/plotting/plot.py
- ants/plotting/plot_ortho.py
- ants/plotting/plot_ortho_stack.py
- ants/utils/scalar_rgb_vector.py
- tests/test_bugs.py
- tests/test_ops.py
- tests/test_plotting.py
This PR expands tests for plotting and ops slightly.
> TESTS: expand tests for ops and plotting

- ants/core/ants_image_io.py
- ants/internal.py
- tests/test_bugs.py
If you try to create an ants image from an array with an unsupported numpy dtype, it just fails. Since we only support 4 dtypes, we really should support automatically casting unsupported dtypes to supported ones. This PR does that.
The one question I have is whether it is good to warn the user that their data is being casted or to just do it silently. Having a bunch of warnings is annoying and pollutes the console, but I can see some people being confused that their data is in a different dtype otherwise.
Below is an example that fails.  The `int16` type is quite common for segmentation arrays which is how I discovered the error:
```python
import ants
arr = np.random.randn(100,100).astype('int16')
img = ants.from_numpy(arr)
```
> FIX: cast unsupported numpy dtypes in ants.from_numpy()

- ants/core/ants_image_io.py
- ants/ops/crop_image.py
- ants/ops/reorient_image.py
- ants/ops/resample_image.py
- tests/test_utils.py
This PR supports cropping vector images and does some small clean up / expansion of support for the "channels_first" property of vector images which is relevant for converting to numpy.
> ENH: crop vector images

- Dockerfile
Something under the hood is causing the mamba solver to fail, reproduced on my Ubuntu machine as well as on the GHA runner. Using the classic solver appears to fix it
> COMP: Docker build suddenly stopped working, needs classic solver

- ants/segmentation/joint_label_fusion.py
- tests/test_segmentation.py
A couple of places had the wrong name for the `type_of_transform` parameter to ants.registration.
> BUG: fix paste error from R, arg is type_of_transform

- ants/registration/affine_initializer.py
Looks like there is a typo in the doc/comment for affine_initializer(), so I fixed it with this pull request.
Here is the change:
This is a **arapper** for  -> This is a **wrapper** for
> fix typo in affine_initializer()

- Dockerfile
Trying to understand intermittent GHA failures
> CI: Update Dockerfile

- .github/workflows/wheels.yml
- README.md
Wheels for Windows and Mac may as well go to PyPI in addition to the Linux ones.
Added a note to README about the Mac compatibility issues
> CI: Push more wheels to pypi, document Mac compatibility issues

- pyproject.toml
Latest numpy and statsmodels don't play nicely together. Have to downgrade one or the other for now
https://github.com/statsmodels/statsmodels/issues/9333#issuecomment-2305438605
> COMP: downgrade numpy for arm64

- ants/ops/denoise_image.py
Same default as ANTs DenoiseImage
> ENH: Default to 2 voxel radius for denoise_image.py

- CMakeLists.txt
- scripts/build_itk.sh
This might affect wheel size, making a PR so I can make some wheels to compare
> PERF: more optimization at compile time

- ants/label/label_overlap_measures.py
One way of addressing the following warning:
```python
>>> meas = ants.label_overlap_measures(dkt, dkt_repaired)
/Users/ntustison/anaconda3/lib/python3.11/site-packages/ants/label/label_overlap_measures.py:43: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame
See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
df.Label[0] = "All"
```
> DISP:  Address pd warning.

- ants/label/__init__.py
- ants/label/label_image_centroids.py
- ants/label/make_points_image.py
- ants/registration/affine_initializer.py
- ants/utils/mni2tal.py
- tests/test_utils.py
BUG: make_points_image function not imported
ENH: New tests for label stats and make_points_image
STYLE: Clean up whitespace and unescaped chars in comments
> BUG: label_image_centroids only worked with sequential labels 1..N

- docs/source/conf.py
RTD builds have been failing for a while
> DOC: remove reference to ants/lib which no longer exists

- src/antsImageToImageMetric.h
Need to add destructor for memory allocated with new in the wrap function
> WIP: Fix nanobind memory leaks

- ants/registration/__init__.py
- ants/registration/registration.py
- tests/test_registration.py
@stnava , @cookpa --- I was going to send an email regarding this work but figured it would be easiest to put all the information in a possible pull request.
With the segmentation networks developed over at ANTsXNet, I've been leveraging that information for registration and I figured the functionality might be useful for the community. Basic usage takes respective sets of fixed and label images, converts them to sets of single label images and calculates the centers-of-mass of all the labels. Those centers-of-mass are used to quickly compute a linear transform using ants.fit_transform_to_paired_points. The single label images (and optional intensity images) are used as input to one of the antsRegistrationSyN* deformable-only calls. I've also been playing with this for masked lesion …
> ENH:  Add label iamge registration and tests.

- ants/registration/registration.py
Adds the option to configure `--float` in `ants.registration`. This feature already exists for `ants.apply_transforms`.
> Make precision (--float) configurable for registration

- ants/label/label_overlap_measures.py
> ENH: Prevent pandas type conversion warning

- scripts/configure_ITK.bat
Trying to fix ITK libtiff issues
> COMP: Bump ITK for Windows

- ants/core/ants_image_io.py
- tests/test_core_ants_image.py
The documentation for this function says you can use a numpy or ITK datatype string when cloning, but only ITK types were supported.
> Allow numpy datatypes in image_clone

- ants/registration/registration.py
Hey fellas. This isn't a proper pull request because I haven't done any tests (I'm not actually sure what to do re standards for this library?); rather, I've just I've just made the registrations.py file a little more reader-friendly.
I'm trying to use ANTsPy to register light-sheet microscopy data of larval zebrafish brains, but am having limited success. I'm having to dig through the code to understand what arguments go where, which I find easier to do after renaming and reorganising a few things.
My hope is that now, if a person wants to understand a specific type of transform, they can read how the arguments `args` are constructed and work backwards from there.
- by comparing this [Anatomy of an antsRegistration call](https://github.com/ANTsX/ANTs/wiki/Anatomy-of-an-antsRegistration-ca …
> Neatened things up to be more reader-friendly

- ants/registration/registration.py
Left an option for backwards compatibility, with a note that users should prefer ants.histogram_match2.
> Turn off hard-coded histogram matching in registration

- ants/core/ants_image_io.py
- src/itkPyBuffer.hxx
- src/readImage.cxx
- tests/test_core_ants_image_io.py
Fixes #773 
I've been staring at this a while and I can't see a case where the "fortran contiguous" data would correctly read into an ITK image. It might have the right shape but it seems that the voxels would be wrong. 
In any case, as used, the code always copies the data into a C-contiguous array (the default).
> No swap numpy dims

- ants/plotting/plot_ortho.py
I have noticed that the vertical line of sagittal image in the `plot_ortho` was flipped.
> fix: vertical line (xyz-lines) in sagittal image of plot_ortho is flipped

- ants/plotting/plot_ortho_stack.py
When `xyz_lines` and `xyz` are set.
> fix: vertical line in sagittal view is flipped

- ants/core/ants_image.py
- tests/test_core_ants_image.py
Because `antsImage.py` did not explicitly define `__iter__`, Python builtin iterator methods would call `__getitem__` directly, which breaks the object state.
Example:
```
im = ants.image_read('t1w.nii.gz')
im.sum() # works
sum(im) # error
im.sum() # now also errors
im[0,0,0] # now also errors
```
To prevent this, I added `__iter__` which raises a TypeError. Built-in iteration methods like sum() can be much slower than using numpy, so I didn't want to enable that.
> ENH: Prevent attempts to iterate over antsImage

- ants/label/label_geometry_measures.py
- tests/test_segmentation.py
Fixing #783 
Add some tests for correct column names, and check return types. Labels should be ints.
Add same test to the function itself, and clean up extra numpy import statements.
> Label geom test

- pyproject.toml
Looks like nanobind 2.6 requires python 3.12
> COMP: Nanobind version limit for older Python

- .github/workflows/wheels.yml
Remove python 3.9 for Mac and Windows - trying to not run out of space again.
> CI: Send all wheels to pypi

- ants/deeplearn/randomly_transform_image_data.py
- ants/registration/create_jacobian_determinant_image.py
- ants/registration/landmark_transforms.py
- ants/utils/__init__.py
- ants/utils/convergence_monitoring.py
- ants/utils/polar_decomposition.py
- tests/test_utils.py
https://github.com/ANTsX/ANTsPy/issues/818
> ENH:  Add polar decomposition and convergence monitoring.

- pyproject.toml
- requirements.txt
statsmodels needs scipy < 1.16 for now. This will be fixed later
> COMP: don't use latest scipy

- .github/workflows/wheels.yml
Push sdist and wheels for all platforms in one go. Use job dependency so partial releases don't happen again
> Pypi workflow

- ants/core/ants_image.py
Before, setting a direction with the wrong number of dimensions raised an error that said the origin had incorrect dimension. I have changed the error message to correctly reference the direction.
fixes #845
> fix: setting incorrect direction raises descriptive error

- ants/label/label_geometry_measures.py
- ants/label/label_stats.py
- src/labelStats.cxx
- tests/test_utils.py
To save an unnecessary clone, we were lazily cloning the data but if the labels are actually uint32, the variable wasn't properly initialized.
For label_stats, add checks that labels are unsigned. Also re-index data in the returned DF by label - it was previously sorted by label, but the pandas index was not updated, so a merge on index would be wrong
> BUG: label_geometry_measures with uint32 labels

- ants/core/__init__.py
- ants/core/ants_image_io.py
- ants/utils/__init__.py
- ants/utils/nifti_utils.py
- src/main.cpp
- src/readImageMetadata.cxx
- src/readImageMetadata.h
- tests/test_utils.py
Working on a solution to #854
This allows us to read ITK image metadata using ImageIO. Thus we can get both qform and sform.
This could be used to make a function that lets one choose which transform to use on read.
> ENH: Read ITK metadata from image on disk
