ANTsX/ANTsPy

ants/registration/interface.py
Sorry for missing a couple the first time. Tested on my end. SynBold to SyNBold; SynBoldAffineto SyNBoldAffine;
=> Fixed remaining typos

ants/utils/__init__.py, ants/utils/functional_lung_segmentation.py, docs/source/utils.rst
https://pubmed.ncbi.nlm.nih.gov/21837781/
=> ENH:  Add functional_lung_segmentation

ants/segmentation/kelly_kapowski.py, scripts/configure_ANTsPy.sh
Will update the ANTs git tag after this pull request.  https://github.com/ANTsX/ANTs/pull/1115
=> ENH:  Reconcile default values.

setup.py
See https://pypi.org/project/sklearn/
=> Remove redundant sklearn dependency

ants/registration/interface.py, ants/utils/get_ants_data.py
Hey @stnava, I refactored ``get_ants_data`` similar to ``get_antsxnet_data`` prior to using ``tf.keras.utils``.  We can add other data but figured we should get the functionality working first.
=> Refactor get_ants_data

ants/core/ants_transform_io.py
infer dimension from file if not provided
=> fixes #319

ants/core/ants_image.py
=> Optimize image indexing by caching array

ants/utils/image_similarity.py
clarifying that function actually returns negative similarity.
=> Clarify documentation

ants/registration/interface.py
Addressing https://github.com/ANTsX/ANTsPy/issues/359
=> ENH:  Check image dimensions.

ants/registration/interface.py
Also cleanup some old code and check that inputs have the correct type
Fixes #364
Fixes #375
=> ENH: Catch registration failures and raise an exception

ants/registration/interface.py
=> ENH: Show registration command line options if verbose

README.md
Hi all,
this is just adding a link to the discussion which is mentioned in the text. I hope this makes it easier for people to join the discusssion.
Best,
Robert
=> add a link to the discussion

ants/registration/interface.py
See https://github.com/ANTsX/ANTs/pull/1411
=> ENH:  Remove learn rate once option.

.github/workflows/wheels.yml
Upload individual wheel artifacts, so people don't have to download all of them
=> ENH: Separate wheel artifacts

.github/workflows/wheels.yml, scripts/configure_ANTsPy.bat, scripts/configure_ANTsPy.sh, scripts/configure_ANTsPy_windows.sh
Also add testing to wheel build routine
=> ENH: Read / Write windows pointers

ants/registration/apply_transforms.py
=> ENH: applytransforms: dont force compose as nii.gz

.readthedocs.yaml
Readthedocs will start requiring this config file soon
=> COMP: Migrate RTD to new config

ants/contrib/sampling/affine3d.py
Added a function Affine3D to enable use of a generic affine transformation.
Also made minor correction to comments for Translate3D
=> Affine updates

ants/registration/interface.py
add more explanation to flow_sigma / total_sigma in registration docs
=> update reg docs

.github/workflows/code-coverage.yml
Adding a workflow dispatch to allow coverage tests on other branches
=> ENH: allow workflow dispatch

.github/workflows/code-coverage.yml
It's built into workflow dispatch
=> ENH: Don't need extra parameter for branch

ants/core/ants_image.py, tests/test_core_ants_image.py
Adds ops with ants on right-side of formula.. so you can do 1 + img, 1 * img, 1 - img, etc.
=> rightside ops

.github/ISSUE_TEMPLATE/bug_report.md
With instructions on how to provide system info
=> DOC: Update issue template

CONTRIBUTING.md, ants/lib/ANTsVersionConfig.h, ants/lib/LOCAL_antsImageClone.cxx, ants/lib/LOCAL_antsImageToImageMetric.h, ants/lib/LOCAL_antsTransform.cxx, ants/lib/LOCAL_composeDisplacementFields.cxx, ants/lib/LOCAL_fitBsplineDisplacementField.cxx, ants/lib/LOCAL_fitBsplineDisplacementFieldToScatteredData.cxx, ants/lib/LOCAL_fitBsplineObjectToScatteredData.cxx, ants/lib/LOCAL_fitThinPlateSplineDisplacementFieldToScatteredData.cxx, ants/lib/LOCAL_integrateVelocityField.cxx, ants/lib/LOCAL_invertDisplacementField.cxx, ants/lib/LOCAL_mergeChannels.cxx, ants/lib/LOCAL_simulateDisplacementField.cxx, ants/lib/ReadWriteData.h, scripts/configure_ANTsPy.bat, scripts/configure_ANTsPy.sh, scripts/configure_ITK.bat, scripts/configure_ITK.sh
Fixes #583 
ITK and ANTs update, also replace Allocate with AllocateInitialized in local C++ functions
=> ENH: Bump ITK and ANTs, initialize all memory allocated for images

ants/lib/LOCAL_antsImageToImageMetric.h
https://github.com/ANTsX/ANTsPy/issues/602
=> ENH:  Add Mattes.

CONTRIBUTING.md, README.md
This PR updates the Readme and the CONTRIBUTING docs a bit.
=> DOCS: update docs

ants/utils/matrix_image.py
This removes the function within a function that was potentially causes windows build errors. It should not change the functionality at all.
=> FIX: remove listfunc from `matrix_to_image´

ants/ops/resample_image.py, ants/registration/apply_transforms.py
For #641 , document the return pixel type from apply_transforms
=> DOC: Clarify return type of apply_transforms

src/fitBsplineObjectToScatteredData.cxx
https://github.com/ANTsX/ANTsPy/issues/660
=> BUG:  Return variable.

.github/workflows/wheels.yml, .github/workflows/wheels_faster.yml
manylinux2014 no longer working, probably due to Centos 7 EOL
=> ENH: Update cibuildwheel linux

ants/ops/__init__.py, ants/ops/add_noise_to_image.py, ants/ops/hessian_objectness.py, src/addNoiseToImage.cxx, src/hessianObjectness.cxx, src/main.cpp
https://github.com/ANTsX/ANTsR/pull/404
=> WIP:  import hessian objectness itk filter.

src/antsTransform.cxx, tests/test_core_ants_transform.py
=> Fix apply transform to image

ants/registration/registration.py
=> DOC: explain reg transform options

ants/registration/create_warped_grid.py
=> DOC: example typo

ants/registration/build_template.py
Fixes #728 
- delete temporary files unless `output_dir=None`
- if output_dir is specified, save intermediate transforms so user can e.g. warp labels or other modalities to the atlas space
=> Build template: delete temporary files

ants/core/ants_image_io.py, src/antsImageHeaderInfo.cxx, tests/test_core_ants_image_io.py
Non-existent files are caught but empty / bad files caused a seg fault
=> ENH: Throw exception if image cannot be read

.github/workflows/wheels.yml, .github/workflows/wheels_faster.yml
macos12 is about to be deprecated
=> Update mac runner

scripts/configure_ITK.sh, scripts/configure_ITK_External_linux.sh, scripts/configure_ITK_External_mac.sh
@cookpa --- in the short term, can we update just the ITK tag?
=> ENH:  Update ITK Tag.

.github/workflows/ci-pytest.yml, .github/workflows/wheels.yml, .github/workflows/wheels_faster.yml
Not sure this will work for all platforms
=> CI: Python 3.13 wheels

ants/registration/registration.py
Clarify affine parameters 
Fixing #791
=> DOC: Registration usage

ants/core/ants_transform.py
I think this is a typo in docstring..
=> Probable typo in docstring

ants/__init__.py, ants/deeplearn/__init__.py, ants/deeplearn/cropping_and_padding_utilities.py, ants/deeplearn/data_augmentation.py, ants/deeplearn/extract_image_patches.py, ants/deeplearn/histogram_warp_image_intensities.py, ants/deeplearn/randomly_transform_image_data.py, ants/deeplearn/reconstruct_image_from_patches.py, ants/deeplearn/regression_match_image.py, ants/deeplearn/simulate_bias_field.py, docs/requirements.txt, docs/source/deeplearn.rst, pyproject.toml, requirements.txt, tests/run_tests.ps1, tests/run_tests.sh, tests/run_tests_travis.sh, tests/test_deeplearn.py
https://github.com/ANTsX/ANTsPy/pull/801#issuecomment-2827888802
=> ENH:  Migrate ANTsPyNet functionality

ants/utils/sitk_to_ants.py, tests/test_utils.py
Support vector images as well as scalars
=> More sitk imports and tests

ants/deeplearn/__init__.py, ants/deeplearn/one_hot_segmentation.py, ants/deeplearn/reconstruct_image_from_patches.py, tests/test_deeplearn.py
=> ENH:  one-hot xfrms

README.md
Changed links to point to right destinations
=> DOC: Updating broken links in README

ants/__init__.py, pyproject.toml
We're due for a release, unless there's any reason to hold off?
=> COMP: Version bump for release

ants/registration/create_jacobian_determinant_image.py, scripts/configure_ANTs.bat, scripts/configure_ANTs.sh, scripts/configure_ITK.bat
Needed to bump ITK / ANTs for windows
=> Fix def grad windows

ants/registration/registration.py
Centralize deterministic vs. non-deterministic behavior setting.
=> BUG:  Remove isolated deterministic handling.

ants/ops/mask_image.py
=> BUG: Need to clone to float

ants/utils/nifti_utils.py
=> BUG: exported function names in nifti_utils.py
